Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/puma/Projects/TUI/mock-dynamo/src
      Runtime: python3.8
      Architectures:
        - x86_64